export const names = [
  {
    name: "Avery",
    gender: "unisex",
    meaning: "ruler of the elves",
    origin: "English",
    popularity: 420,
  },
  {
    name: "Evelyn",
    gender: "female",
    meaning: "wished for child",
    origin: "English",
    popularity: 24,
  },
  {
    name: "Luna",
    gender: "female",
    meaning: "moon",
    origin: "Latin",
    popularity: 10,
  },
  {
    name: "Milo",
    gender: "male",
    meaning: "soldier",
    origin: "German",
    popularity: 140,
  },
  {
    name: "Silas",
    gender: "male",
    meaning: "forest",
    origin: "Latin",
    popularity: 91,
  },
  {
    name: "Charlotte",
    gender: "female",
    meaning: "free woman",
    origin: "French",
    popularity: 3,
  },
  {
    name: "Olivia",
    gender: "female",
    meaning: "olive tree",
    origin: "Latin",
    popularity: 1,
  },
  {
    name: "Emma",
    gender: "female",
    meaning: "universal",
    origin: "German",
    popularity: 2,
  },
  {
    name: "Harper",
    gender: "unisex",
    meaning: "harp player",
    origin: "English",
    popularity: 12,
  },
  {
    name: "Amelia",
    gender: "female",
    meaning: "work",
    origin: "Latin",
    popularity: 4,
  },
  {
    name: "Isabella",
    gender: "female",
    meaning: "pledged to God",
    origin: "Hebrew",
    popularity: 6,
  },
  {
    name: "Sophia",
    gender: "female",
    meaning: "wisdom",
    origin: "Greek",
    popularity: 5,
  },
  {
    name: "Mia",
    gender: "female",
    meaning: "mine",
    origin: "Italian",
    popularity: 7,
  },
  {
    name: "Eli",
    gender: "male",
    meaning: "uplifted",
    origin: "Hebrew",
    popularity: 40,
  },
  {
    name: "Noah",
    gender: "male",
    meaning: "rest",
    origin: "Hebrew",
    popularity: 1,
  },
  {
    name: "Liam",
    gender: "male",
    meaning: "strong protector",
    origin: "Irish",
    popularity: 2,
  },
  {
    name: "James",
    gender: "male",
    meaning: "supplanter",
    origin: "Hebrew",
    popularity: 4,
  },
  {
    name: "Henry",
    gender: "male",
    meaning: "estate ruler",
    origin: "German",
    popularity: 9,
  },
  {
    name: "Logan",
    gender: "unisex",
    meaning: "little hollow",
    origin: "Scottish",
    popularity: 16,
  },
  {
    name: "Elijah",
    gender: "male",
    meaning: "my God is Yahweh",
    origin: "Hebrew",
    popularity: 5,
  },
  {
    name: "Benjamin",
    gender: "male",
    meaning: "son of the right hand",
    origin: "Hebrew",
    popularity: 7,
  },
  {
    name: "Wyatt",
    gender: "male",
    meaning: "brave at war",
    origin: "English",
    popularity: 29,
  },
  {
    name: "Hudson",
    gender: "male",
    meaning: "son of Hugh",
    origin: "English",
    popularity: 34,
  },
  {
    name: "Levi",
    gender: "male",
    meaning: "joined",
    origin: "Hebrew",
    popularity: 12,
  },
  {
    name: "Ella",
    gender: "female",
    meaning: "fairy maiden",
    origin: "German",
    popularity: 15,
  },
  {
    name: "Aubrey",
    gender: "unisex",
    meaning: "elf ruler",
    origin: "German",
    popularity: 180,
  },
  {
    name: "Nora",
    gender: "female",
    meaning: "light",
    origin: "Irish",
    popularity: 28,
  },
  {
    name: "Scarlett",
    gender: "female",
    meaning: "red",
    origin: "English",
    popularity: 20,
  },
  {
    name: "Aria",
    gender: "female",
    meaning: "song",
    origin: "Italian",
    popularity: 11,
  },
  {
    name: "Hazel",
    gender: "female",
    meaning: "hazel tree",
    origin: "English",
    popularity: 31,
  },
  {
    name: "Grayson",
    gender: "male",
    meaning: "son of the steward",
    origin: "English",
    popularity: 35,
  },
  {
    name: "Jackson",
    gender: "male",
    meaning: "son of Jack",
    origin: "English",
    popularity: 23,
  },
  {
    name: "Carter",
    gender: "unisex",
    meaning: "cart driver",
    origin: "English",
    popularity: 39,
  },
  {
    name: "Layla",
    gender: "female",
    meaning: "night",
    origin: "Arabic",
    popularity: 14,
  },
  {
    name: "Aiden",
    gender: "male",
    meaning: "little fire",
    origin: "Irish",
    popularity: 26,
  },
  {
    name: "Chloe",
    gender: "female",
    meaning: "blooming",
    origin: "Greek",
    popularity: 18,
  },
  {
    name: "Madison",
    gender: "female",
    meaning: "son of Matthew",
    origin: "English",
    popularity: 78,
  },
  {
    name: "Willow",
    gender: "female",
    meaning: "willow tree",
    origin: "English",
    popularity: 37,
  },
  {
    name: "Zoe",
    gender: "female",
    meaning: "life",
    origin: "Greek",
    popularity: 38,
  },
  {
    name: "Penelope",
    gender: "female",
    meaning: "weaver",
    origin: "Greek",
    popularity: 21,
  },
  {
    name: "Riley",
    gender: "unisex",
    meaning: "courageous",
    origin: "Irish",
    popularity: 32,
  },
  {
    name: "Hunter",
    gender: "male",
    meaning: "one who hunts",
    origin: "English",
    popularity: 97,
  },
  {
    name: "Caleb",
    gender: "male",
    meaning: "faithful",
    origin: "Hebrew",
    popularity: 56,
  },
  {
    name: "Easton",
    gender: "male",
    meaning: "east town",
    origin: "English",
    popularity: 66,
  },
  {
    name: "Cooper",
    gender: "male",
    meaning: "barrel maker",
    origin: "English",
    popularity: 49,
  },
  {
    name: "Paisley",
    gender: "female",
    meaning: "church",
    origin: "Scottish",
    popularity: 53,
  },
  {
    name: "Grace",
    gender: "female",
    meaning: "grace",
    origin: "Latin",
    popularity: 34,
  },
  {
    name: "Addison",
    gender: "unisex",
    meaning: "son of Adam",
    origin: "English",
    popularity: 156,
  },
  {
    name: "Maverick",
    gender: "male",
    meaning: "independent",
    origin: "American",
    popularity: 47,
  },
  {
    name: "Piper",
    gender: "female",
    meaning: "pipe player",
    origin: "English",
    popularity: 91,
  },
  {
    name: "Oakley",
    gender: "unisex",
    meaning: "oak meadow",
    origin: "English",
    popularity: 32,
  },
  {
    name: "Finely",
    gender: "female",
    meaning: "fair-haired hero",
    origin: "Scottish",
    popularity: 48,
  },
  {
    name: "Kinley",
    gender: "female",
    meaning: "fair hero",
    origin: "Galeic",
    popularity: 23,
  },
  {
    name: "Kinsley",
    gender: "female",
    meaning: "king's meadow",
    origin: "English",
    popularity: 34,
  },
  {
    name: "Bianca",
    gender: "female",
    meaning: "white, pure",
    origin: "Italian",
    popularity: 300,
  },
  {
    name: "Briar",
    gender: "unisex",
    meaning: "thorny bush of wild roses",
    origin: "English",
    popularity: 450,
  },
  {
    name: "Brody",
    gender: "male",
    meaning: "ditch",
    origin: "Gaelic",
    popularity: 110,
  },
  {
    name: "Daisy",
    gender: "female",
    meaning: "day's eye",
    origin: "English",
    popularity: 150,
  },
  {
    name: "Declan",
    gender: "male",
    meaning: "man of prayer",
    origin: "Irish",
    popularity: 90,
  },
  {
    name: "Dean",
    gender: "male",
    meaning: "valley",
    origin: "English",
    popularity: 180,
  },
  {
    name: "Felix",
    gender: "male",
    meaning: "lucky, successful",
    origin: "Latin",
    popularity: 140,
  },
  {
    name: "Freya",
    gender: "female",
    meaning: "noble woman",
    origin: "Norse",
    popularity: 80,
  },
  {
    name: "Genevieve",
    gender: "female",
    meaning: "woman of the family",
    origin: "French",
    popularity: 120,
  },
  {
    name: "Gideon",
    gender: "male",
    meaning: "great warrior",
    origin: "Hebrew",
    popularity: 160,
  },
  {
    name: "Gavin",
    gender: "male",
    meaning: "white hawk",
    origin: "Welsh",
    popularity: 190,
  },
  {
    name: "Isaac",
    gender: "male",
    meaning: "he will laugh",
    origin: "Hebrew",
    popularity: 30,
  },
  {
    name: "Iris",
    gender: "female",
    meaning: "rainbow",
    origin: "Greek",
    popularity: 60,
  },
  {
    name: "Juniper",
    gender: "unisex",
    meaning: "young",
    origin: "Latin",
    popularity: 200,
  },
  {
    name: "Julian",
    gender: "male",
    meaning: "youthful",
    origin: "Latin",
    popularity: 50,
  },
  {
    name: "Kian",
    gender: "male",
    meaning: "ancient",
    origin: "Irish",
    popularity: 250,
  },
  {
    name: "Kaia",
    gender: "female",
    meaning: "earth",
    origin: "Hawaiian",
    popularity: 110,
  },
  {
    name: "Marcus",
    gender: "male",
    meaning: "warlike",
    origin: "Latin",
    popularity: 170,
  },
  {
    name: "Morgan",
    gender: "unisex",
    meaning: "sea circle",
    origin: "Welsh",
    popularity: 280,
  },
  {
    name: "Owen",
    gender: "male",
    meaning: "noble, well born",
    origin: "Welsh",
    popularity: 18,
  },
  {
    name: "Ophelia",
    gender: "female",
    meaning: "help",
    origin: "Greek",
    popularity: 130,
  },
  {
    name: "Quinn",
    gender: "unisex",
    meaning: "descendant of Conn",
    origin: "Irish",
    popularity: 60,
  },
  {
    name: "Quentin",
    gender: "male",
    meaning: "fifth",
    origin: "Latin",
    popularity: 350,
  },
  {
    name: "Quiet",
    gender: "female",
    meaning: "tranquil, silent",
    origin: "English",
    popularity: 900,
  },
  {
    name: "Ronan",
    gender: "male",
    meaning: "little seal",
    origin: "Irish",
    popularity: 70,
  },
  {
    name: "Rose",
    gender: "female",
    meaning: "a flower",
    origin: "Latin",
    popularity: 80,
  },
  {
    name: "Theodore",
    gender: "male",
    meaning: "gift of God",
    origin: "Greek",
    popularity: 8,
  },
  {
    name: "Tristan",
    gender: "male",
    meaning: "sad",
    origin: "Welsh",
    popularity: 100,
  },
  {
    name: "Talia",
    gender: "female",
    meaning: "dew from heaven",
    origin: "Hebrew",
    popularity: 210,
  },
  {
    name: "Uriel",
    gender: "male",
    meaning: "God is my light",
    origin: "Hebrew",
    popularity: 400,
  },
  {
    name: "Una",
    gender: "female",
    meaning: "one, unique",
    origin: "Irish",
    popularity: 700,
  },
  {
    name: "Ursula",
    gender: "female",
    meaning: "little bear",
    origin: "Latin",
    popularity: 850,
  },
  {
    name: "Victor",
    gender: "male",
    meaning: "conqueror",
    origin: "Latin",
    popularity: 120,
  },
  {
    name: "Vincent",
    gender: "male",
    meaning: "conquering",
    origin: "Latin",
    popularity: 130,
  },
  {
    name: "Violet",
    gender: "female",
    meaning: "purple",
    origin: "Latin",
    popularity: 30,
  },
  {
    name: "Vivian",
    gender: "unisex",
    meaning: "life",
    origin: "Latin",
    popularity: 55,
  },
  {
    name: "Wren",
    gender: "unisex",
    meaning: "small bird",
    origin: "English",
    popularity: 100,
  },
  {
    name: "Xavier",
    gender: "male",
    meaning: "new house",
    origin: "Basque",
    popularity: 65,
  },
  {
    name: "Xander",
    gender: "male",
    meaning: "defender of men",
    origin: "Greek",
    popularity: 95,
  },
  {
    name: "Xia",
    gender: "female",
    meaning: "glow of the sun",
    origin: "Chinese",
    popularity: 500,
  },
  {
    name: "Xylia",
    gender: "female",
    meaning: "of the wood",
    origin: "Greek",
    popularity: 650,
  },
  {
    name: "Yusuf",
    gender: "male",
    meaning: "God increases",
    origin: "Arabic",
    popularity: 380,
  },
  {
    name: "Yiannis",
    gender: "male",
    meaning: "God is gracious",
    origin: "Greek",
    popularity: 700,
  },
  {
    name: "Yara",
    gender: "female",
    meaning: "small butterfly",
    origin: "Arabic",
    popularity: 200,
  },
  {
    name: "Yael",
    gender: "unisex",
    meaning: "mountain goat",
    origin: "Hebrew",
    popularity: 550,
  },
  {
    name: "Zachary",
    gender: "male",
    meaning: "the Lord has remembered",
    origin: "Hebrew",
    popularity: 75,
  },
  {
    name: "Zane",
    gender: "male",
    meaning: "God is gracious",
    origin: "Hebrew",
    popularity: 110,
  },
  {
    name: "Zara",
    gender: "female",
    meaning: "princess",
    origin: "Arabic",
    popularity: 50,
  },
    {
    name: "Adeline",
    gender: "female",
    meaning: "noble",
    origin: "French",
    popularity: 72,
  },
  {
    name: "Alden",
    gender: "male",
    meaning: "old friend",
    origin: "English",
    popularity: 310,
  },
  {
    name: "Alina",
    gender: "female",
    meaning: "bright, beautiful",
    origin: "Slavic",
    popularity: 145,
  },
  {
    name: "Amos",
    gender: "male",
    meaning: "carried by God",
    origin: "Hebrew",
    popularity: 240,
  },
  {
    name: "Ansel",
    gender: "male",
    meaning: "with divine protection",
    origin: "German",
    popularity: 460,
  },
  {
    name: "Ariadne",
    gender: "female",
    meaning: "most holy",
    origin: "Greek",
    popularity: 330,
  },
  {
    name: "Asa",
    gender: "unisex",
    meaning: "healer",
    origin: "Hebrew",
    popularity: 270,
  },
  {
    name: "Atlas",
    gender: "male",
    meaning: "to endure",
    origin: "Greek",
    popularity: 120,
  },
  {
    name: "Aurelia",
    gender: "female",
    meaning: "golden",
    origin: "Latin",
    popularity: 190,
  },
  {
    name: "Beau",
    gender: "male",
    meaning: "handsome",
    origin: "French",
    popularity: 90,
  },
  {
    name: "Bellamy",
    gender: "unisex",
    meaning: "fine friend",
    origin: "French",
    popularity: 350,
  },
  {
    name: "Bennett",
    gender: "male",
    meaning: "blessed",
    origin: "Latin",
    popularity: 95,
  },
  {
    name: "Blair",
    gender: "unisex",
    meaning: "field, plain",
    origin: "Scottish",
    popularity: 210,
  },
  {
    name: "Bria",
    gender: "female",
    meaning: "noble, strong",
    origin: "Irish",
    popularity: 320,
  },
  {
    name: "Callahan",
    gender: "male",
    meaning: "bright-headed",
    origin: "Irish",
    popularity: 400,
  },
  {
    name: "Callie",
    gender: "female",
    meaning: "beautiful",
    origin: "Greek",
    popularity: 170,
  },
  {
    name: "Camila",
    gender: "female",
    meaning: "young ceremonial attendant",
    origin: "Latin",
    popularity: 11,
  },
  {
    name: "Casper",
    gender: "male",
    meaning: "treasurer",
    origin: "Persian",
    popularity: 410,
  },
  {
    name: "Cassidy",
    gender: "unisex",
    meaning: "curly-haired",
    origin: "Irish",
    popularity: 370,
  },
  {
    name: "Cecilia",
    gender: "female",
    meaning: "blind",
    origin: "Latin",
    popularity: 132,
  },
  {
    name: "Celia",
    gender: "female",
    meaning: "heavenly",
    origin: "Latin",
    popularity: 380,
  },
  {
    name: "Clark",
    gender: "male",
    meaning: "scribe",
    origin: "English",
    popularity: 300,
  },
  {
    name: "Cleo",
    gender: "unisex",
    meaning: "pride, glory",
    origin: "Greek",
    popularity: 295,
  },
  {
    name: "Clara",
    gender: "female",
    meaning: "bright, clear",
    origin: "Latin",
    popularity: 103,
  },
  {
    name: "Clyde",
    gender: "male",
    meaning: "warm, friendly",
    origin: "Scottish",
    popularity: 520,
  },
  {
    name: "Coraline",
    gender: "female",
    meaning: "coral",
    origin: "English",
    popularity: 350,
  },
  {
    name: "Crew",
    gender: "male",
    meaning: "group",
    origin: "English",
    popularity: 220,
  },
  {
    name: "Cyrus",
    gender: "male",
    meaning: "sun",
    origin: "Persian",
    popularity: 440,
  },
  {
    name: "Dahlia",
    gender: "female",
    meaning: "valley flower",
    origin: "Swedish",
    popularity: 150,
  },
  {
    name: "Damon",
    gender: "male",
    meaning: "to tame",
    origin: "Greek",
    popularity: 260,
  },
  {
    name: "Darcy",
    gender: "unisex",
    meaning: "dark-haired",
    origin: "French",
    popularity: 510,
  },
  {
    name: "Delaney",
    gender: "female",
    meaning: "descendant of the challenger",
    origin: "Irish",
    popularity: 210,
  },
  {
    name: "Della",
    gender: "female",
    meaning: "noble",
    origin: "German",
    popularity: 470,
  },
  {
    name: "Desmond",
    gender: "male",
    meaning: "from South Munster",
    origin: "Irish",
    popularity: 370,
  },
  {
    name: "Dorian",
    gender: "male",
    meaning: "of Dorus",
    origin: "Greek",
    popularity: 340,
  },
  {
    name: "Elara",
    gender: "female",
    meaning: "bright, shining",
    origin: "Greek",
    popularity: 410,
  },
  {
    name: "Elodie",
    gender: "female",
    meaning: "marsh flower",
    origin: "French",
    popularity: 280,
  },
  {
    name: "Eloise",
    gender: "female",
    meaning: "healthy",
    origin: "French",
    popularity: 95,
  },
  {
    name: "Ember",
    gender: "unisex",
    meaning: "spark",
    origin: "English",
    popularity: 260,
  },
  {
    name: "Emery",
    gender: "unisex",
    meaning: "brave, powerful",
    origin: "German",
    popularity: 130,
  },
  {
    name: "Emmett",
    gender: "male",
    meaning: "universal",
    origin: "German",
    popularity: 150,
  },
  {
    name: "Esther",
    gender: "female",
    meaning: "star",
    origin: "Hebrew",
    popularity: 140,
  },
  {
    name: "Everest",
    gender: "unisex",
    meaning: "dweller on the river bank",
    origin: "English",
    popularity: 300,
  },
  {
    name: "Everly",
    gender: "female",
    meaning: "boar meadow",
    origin: "English",
    popularity: 75,
  },
  {
    name: "Ezra",
    gender: "male",
    meaning: "help",
    origin: "Hebrew",
    popularity: 8,
  },
  {
    name: "Faye",
    gender: "female",
    meaning: "fairy",
    origin: "English",
    popularity: 390,
  },
  {
    name: "Finnegan",
    gender: "male",
    meaning: "fair",
    origin: "Irish",
    popularity: 210,
  },
  {
    name: "Fiona",
    gender: "female",
    meaning: "white, fair",
    origin: "Scottish",
    popularity: 296,
  },
  {
    name: "Foster",
    gender: "male",
    meaning: "forester",
    origin: "English",
    popularity: 380,
  },
  {
    name: "Gemma",
    gender: "female",
    meaning: "precious stone",
    origin: "Italian",
    popularity: 160,
  },
  {
    name: "Giana",
    gender: "female",
    meaning: "God is gracious",
    origin: "Italian",
    popularity: 310,
  },
  {
    name: "Gideon",
    gender: "male",
    meaning: "feller",
    origin: "Hebrew",
    popularity: 260,
  },
  {
    name: "Greer",
    gender: "unisex",
    meaning: "watchful",
    origin: "Scottish",
    popularity: 520,
  },
  {
    name: "Hallie",
    gender: "female",
    meaning: "dweller at the meadow",
    origin: "English",
    popularity: 200,
  },
  {
    name: "Hamish",
    gender: "male",
    meaning: "supplanter",
    origin: "Scottish",
    popularity: 620,
  },
  {
    name: "Harlow",
    gender: "unisex",
    meaning: "army hill",
    origin: "English",
    popularity: 150,
  },
  {
    name: "Hattie",
    gender: "female",
    meaning: "home ruler",
    origin: "German",
    popularity: 300,
  },
  {
    name: "Hayes",
    gender: "male",
    meaning: "hedged area",
    origin: "English",
    popularity: 250,
  },
  {
    name: "Henley",
    gender: "unisex",
    meaning: "high meadow",
    origin: "English",
    popularity: 240,
  },
  {
    name: "Hugo",
    gender: "male",
    meaning: "mind, spirit",
    origin: "German",
    popularity: 180,
  },
  {
    name: "Imani",
    gender: "female",
    meaning: "faith",
    origin: "Swahili",
    popularity: 330,
  },
  {
    name: "Indie",
    gender: "female",
    meaning: "independent",
    origin: "English",
    popularity: 290,
  },
  {
    name: "Ingrid",
    gender: "female",
    meaning: "beautiful, beloved",
    origin: "Norse",
    popularity: 340,
  },
  {
    name: "Isla",
    gender: "female",
    meaning: "island",
    origin: "Scottish",
    popularity: 33,
  },
  {
    name: "Ivan",
    gender: "male",
    meaning: "God is gracious",
    origin: "Russian",
    popularity: 140,
  },
  {
    name: "Jada",
    gender: "female",
    meaning: "wise",
    origin: "Hebrew",
    popularity: 280,
  },
  {
    name: "Jasper",
    gender: "male",
    meaning: "treasurer",
    origin: "Persian",
    popularity: 154,
  },
  {
    name: "Jenna",
    gender: "female",
    meaning: "white shadow",
    origin: "English",
    popularity: 400,
  },
  {
    name: "Jett",
    gender: "male",
    meaning: "jet black",
    origin: "English",
    popularity: 230,
  },
  {
    name: "Jolie",
    gender: "female",
    meaning: "pretty",
    origin: "French",
    popularity: 430,
  },
  {
    name: "Kade",
    gender: "male",
    meaning: "round",
    origin: "English",
    popularity: 310,
  },
  {
    name: "Kael",
    gender: "male",
    meaning: "thin",
    origin: "Gaelic",
    popularity: 520,
  },
  {
    name: "Kairo",
    gender: "male",
    meaning: "victorious",
    origin: "Arabic",
    popularity: 190,
  },
  {
    name: "Keaton",
    gender: "male",
    meaning: "shed town",
    origin: "English",
    popularity: 360,
  },
  {
    name: "Kendall",
    gender: "unisex",
    meaning: "valley of the River Kent",
    origin: "English",
    popularity: 300,
  },
  {
    name: "Kendrick",
    gender: "male",
    meaning: "royal ruler",
    origin: "English",
    popularity: 400,
  },
  {
    name: "Kehlani",
    gender: "female",
    meaning: "sea heaven",
    origin: "Hawaiian",
    popularity: 90,
  },
  {
    name: "Kira",
    gender: "female",
    meaning: "throne",
    origin: "Russian",
    popularity: 350,
  },
  {
    name: "Knox",
    gender: "male",
    meaning: "round hill",
    origin: "Scottish",
    popularity: 240,
  },
  {
    name: "Kyler",
    gender: "male",
    meaning: "narrow strait",
    origin: "Dutch",
    popularity: 380,
  },
  {
    name: "Lachlan",
    gender: "male",
    meaning: "from the fjord land",
    origin: "Scottish",
    popularity: 450,
  },
  {
    name: "Laila",
    gender: "female",
    meaning: "night beauty",
    origin: "Arabic",
    popularity: 215,
  },
  {
    name: "Lana",
    gender: "female",
    meaning: "rock",
    origin: "Slavic",
    popularity: 230,
  },
  {
    name: "Lara",
    gender: "female",
    meaning: "protection",
    origin: "Greek",
    popularity: 260,
  },
  {
    name: "Laurence",
    gender: "male",
    meaning: "from Laurentum",
    origin: "Latin",
    popularity: 540,
  },
  {
    name: "Leighton",
    gender: "unisex",
    meaning: "from the meadow town",
    origin: "English",
    popularity: 210,
  },
  {
    name: "Leland",
    gender: "male",
    meaning: "meadow land",
    origin: "English",
    popularity: 350,
  },
  {
    name: "Lilith",
    gender: "female",
    meaning: "night creature",
    origin: "Hebrew",
    popularity: 290,
  },
  {
    name: "Liora",
    gender: "female",
    meaning: "my light",
    origin: "Hebrew",
    popularity: 480,
  },
  {
    name: "Lorelei",
    gender: "female",
    meaning: "alluring",
    origin: "German",
    popularity: 340,
  },
  {
    name: "Lucian",
    gender: "male",
    meaning: "light",
    origin: "Latin",
    popularity: 390,
  },
  {
    name: "Maeve",
    gender: "female",
    meaning: "she who intoxicates",
    origin: "Irish",
    popularity: 25,
  },
  {
    name: "Magnus",
    gender: "male",
    meaning: "great",
    origin: "Latin",
    popularity: 510,
  },
  {
    name: "Maisie",
    gender: "female",
    meaning: "pearl",
    origin: "Scottish",
    popularity: 260,
  },
  {
    name: "Marcel",
    gender: "male",
    meaning: "little warrior",
    origin: "French",
    popularity: 420,
  },
  {
    name: "Maren",
    gender: "female",
    meaning: "sea",
    origin: "Latin",
    popularity: 310,
  },
  {
    name: "Matilda",
    gender: "female",
    meaning: "mighty in battle",
    origin: "German",
    popularity: 50,
  },
  {
    name: "Maxton",
    gender: "male",
    meaning: "greatest town",
    origin: "English",
    popularity: 370,
  },
  {
    name: "Meadow",
    gender: "female",
    meaning: "field of grass",
    origin: "English",
    popularity: 420,
  },
  {
    name: "Miriam",
    gender: "female",
    meaning: "beloved",
    origin: "Hebrew",
    popularity: 260,
  },
  {
    name: "Nadia",
    gender: "female",
    meaning: "hope",
    origin: "Slavic",
    popularity: 150,
  },
  {
    name: "Nash",
    gender: "male",
    meaning: "by the ash tree",
    origin: "English",
    popularity: 200,
  },
  {
    name: "Naya",
    gender: "female",
    meaning: "renewal",
    origin: "Indian",
    popularity: 390,
  },
  {
    name: "Neve",
    gender: "female",
    meaning: "snow",
    origin: "Irish",
    popularity: 470,
  },
  {
    name: "Nikolai",
    gender: "male",
    meaning: "victory of the people",
    origin: "Russian",
    popularity: 300,
  },
  {
    name: "Nova",
    gender: "unisex",
    meaning: "new star",
    origin: "Latin",
    popularity: 32,
  },
  {
    name: "Oaklyn",
    gender: "female",
    meaning: "oak lake",
    origin: "American",
    popularity: 190,
  },
  {
    name: "Odin",
    gender: "male",
    meaning: "frenzy, inspiration",
    origin: "Norse",
    popularity: 260,
  },
  {
    name: "Orion",
    gender: "male",
    meaning: "rising in the sky",
    origin: "Greek",
    popularity: 110,
  },
  {
    name: "Palmer",
    gender: "unisex",
    meaning: "pilgrim",
    origin: "English",
    popularity: 160,
  },
  {
    name: "Persephone",
    gender: "female",
    meaning: "bringer of destruction",
    origin: "Greek",
    popularity: 450,
  },
  {
    name: "Porter",
    gender: "male",
    meaning: "gatekeeper",
    origin: "English",
    popularity: 290,
  },
  {
    name: "Primrose",
    gender: "female",
    meaning: "first rose",
    origin: "English",
    popularity: 590,
  },
  {
    name: "Quilla",
    gender: "female",
    meaning: "moon",
    origin: "Incan",
    popularity: 850,
  },
  {
    name: "Raya",
    gender: "female",
    meaning: "friend",
    origin: "Hebrew",
    popularity: 300,
  },
  {
    name: "Remi",
    gender: "unisex",
    meaning: "oarsman",
    origin: "French",
    popularity: 110,
  },
  {
    name: "Remington",
    gender: "unisex",
    meaning: "place on a riverbank",
    origin: "English",
    popularity: 180,
  },
  {
    name: "Rhett",
    gender: "male",
    meaning: "advice",
    origin: "Dutch",
    popularity: 150,
  },
  {
    name: "Rhea",
    gender: "female",
    meaning: "flowing",
    origin: "Greek",
    popularity: 260,
  },
  {
    name: "Rory",
    gender: "unisex",
    meaning: "red king",
    origin: "Irish",
    popularity: 220,
  },
  {
    name: "Rosalie",
    gender: "female",
    meaning: "rose",
    origin: "French",
    popularity: 130,
  },
  {
    name: "Rowan",
    gender: "unisex",
    meaning: "little red one",
    origin: "Irish",
    popularity: 95,
  },
  {
    name: "Sage",
    gender: "unisex",
    meaning: "wise",
    origin: "Latin",
    popularity: 140,
  },
  {
    name: "Salem",
    gender: "unisex",
    meaning: "peace",
    origin: "Hebrew",
    popularity: 210,
  },
  {
    name: "Sarai",
    gender: "female",
    meaning: "princess",
    origin: "Hebrew",
    popularity: 380,
  },
  {
    name: "Saylor",
    gender: "female",
    meaning: "boat worker",
    origin: "English",
    popularity: 140,
  },
  {
    name: "Selah",
    gender: "female",
    meaning: "praise",
    origin: "Hebrew",
    popularity: 320,
  },
  {
    name: "Sienna",
    gender: "female",
    meaning: "orange-red",
    origin: "Italian",
    popularity: 179,
  },
  {
    name: "Silas",
    gender: "male",
    meaning: "wood, forest",
    origin: "Latin",
    popularity: 105,
  },
  {
    name: "Soren",
    gender: "male",
    meaning: "stern",
    origin: "Danish",
    popularity: 290,
  },
  {
    name: "Stella",
    gender: "female",
    meaning: "star",
    origin: "Latin",
    popularity: 41,
  },
  {
    name: "Sutton",
    gender: "unisex",
    meaning: "southern settlement",
    origin: "English",
    popularity: 115,
  },
  {
    name: "Tate",
    gender: "male",
    meaning: "cheerful",
    origin: "English",
    popularity: 240,
  },
  {
    name: "Tegan",
    gender: "female",
    meaning: "fair",
    origin: "Welsh",
    popularity: 330,
  },
  {
    name: "Thalia",
    gender: "female",
    meaning: "to flourish",
    origin: "Greek",
    popularity: 310,
  },
  {
    name: "Thiago",
    gender: "male",
    meaning: "may God protect",
    origin: "Portuguese",
    popularity: 150,
  },
  {
    name: "Tobias",
    gender: "male",
    meaning: "God is good",
    origin: "Hebrew",
    popularity: 210,
  },
  {
    name: "True",
    gender: "unisex",
    meaning: "genuine",
    origin: "English",
    popularity: 980,
  },
  {
    name: "Vera",
    gender: "female",
    meaning: "faith",
    origin: "Russian",
    popularity: 250,
  },
  {
    name: "Vance",
    gender: "male",
    meaning: "marshland",
    origin: "English",
    popularity: 370,
  },
  {
    name: "Vienna",
    gender: "female",
    meaning: "from Vienna",
    origin: "Latin",
    popularity: 210,
  },
  {
    name: "Willa",
    gender: "female",
    meaning: "resolute protection",
    origin: "German",
    popularity: 180,
  },
  {
    name: "Winston",
    gender: "male",
    meaning: "joyful stone",
    origin: "English",
    popularity: 430,
  },
  {
    name: "Winter",
    gender: "female",
    meaning: "the season",
    origin: "English",
    popularity: 240,
  },
  {
    name: "Zadie",
    gender: "female",
    meaning: "princess",
    origin: "Hebrew",
    popularity: 620,
  },
  {
    name: "Zev",
    gender: "male",
    meaning: "wolf",
    origin: "Hebrew",
    popularity: 560,
  },
  {
    name: "Zora",
    gender: "female",
    meaning: "dawn",
    origin: "Slavic",
    popularity: 500,
  }

];